### ISSUE TITLE
Nested arrays appear to not map correctly 

### ISSUE THREAD

**Issue by DylanWatson44** [ahebrank/vscode-yaml2json#1]
Started with this Json
```
{
  "message": {
    "businessPartnerId": "123",
    "paymentMethods": {
      "incoming": {
        "paymentCards": [
          {
            "businessAgreements": [
              {
                "businessAgreement": "234",
                "defaultAmount": "12.00",
                "incomingPaymentMethod": "ONETOUCH"
              }
            ]
          },
          {
            "paymentCardID": "000002"
          }
        ]
      }
    }
  }
}
```

Got this Yaml
```
message:
    businessPartnerId: '123'
    paymentMethods:
        incoming:
            paymentCards:
                -
                    businessAgreements: [{businessAgreement: '234', defaultAmount: '12.00', incomingPaymentMethod: ONETOUCH}]
                -
                    paymentCardID: '000002'
```
The 'businessAgreements' field above has not been properly formatted.
